name: Desafio 01 - Input Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Docker Image"
        required: true
        type: string

jobs:
  scout-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.7.0

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker image pull ${{ inputs.docker_image }}
      
      - name: Show All Images
        run: docker image ls -a

      - name: Docker Scout
        uses: docker/scout-action@v1.18.2
        with:
          command: quickview
          image: ${{ inputs.docker_image }}
